copilot:
  value: true
  description: "Enable Copilot"
dark_mode:
  value: "system"
  description: "Enable dark mode"
  enum: ['system', true, false]
debug_mode:
  value: true
  description: "Enable debug mode"
line_blame:
  value: true
  description: "Show blame information in the gutter"
